uploading doctor's functions
pmarko09/medical-clinic pull request #3
Opened 2024-08-07 20:26 UTC by pmarko09

2024-08-08 09:14 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +    @GetMapping ({"/{email}"})
nie musisz uzywac '{}' w sytuacji kiedy masz tylko jedna sciezke -> te nawiasy wasate uzywamy kiedy chcemy aby jedna metoda mogla byc odpalona przy uzyciu wielu sciezek

2024-08-08 09:14 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +    @DeleteMapping ({"/{email}"})
nie musisz uzywac '{}' w sytuacji kiedy masz tylko jedna sciezke -> te nawiasy wasate uzywamy kiedy chcemy aby jedna metoda mogla byc odpalona przy uzyciu wielu sciezek

2024-08-08 09:15 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +    @PutMapping ({"/{email}"})
nie musisz uzywac '{}' w sytuacji kiedy masz tylko jedna sciezke -> te nawiasy wasate uzywamy kiedy chcemy aby jedna metoda mogla byc odpalona przy uzyciu wielu sciezek

2024-08-08 09:16 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +    @PutMapping ({"/{email}/change-password"})
Ogólnie rzecz biorąc nie ma zazwyczaj sensu używania czasownikow w sciezce!!
Dlaczego?
Ponieważ typ operacji (czasownik) okresla nam metoda HTTP
@PutMapping ({"/{email}/password"})

2024-08-08 09:17 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +    public Doctor changeDoctorPassword (@PathVariable String email, @RequestBody ChangePasswordCommand newPassword) {
public Doctor changeDoctorPassword(@PathVariable String email, @RequestBody ChangePasswordCommand newPassword) {

Nadmiarowa spacja klikajmy ctrl alt l

2024-08-08 09:18 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/exception/DoctorNotFoundException.java
> +    public DoctorNotFoundException (String email) {
spacja nadmiarowa

2024-08-08 09:18 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/exception/DoctorNotFoundException.java
> +        super("Doctor with email " + email + " not found.");
Fajniejszym sposobem na formatowanie Stringa jest uzywanie:
 String.format("Doctor with email %s not found.", email);

2024-08-08 09:19 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/exception/SameDoctorEmailException.java
> +public class SameDoctorEmailException extends RuntimeException{
SameDoctorEmailException -> DoctorAlreadyExistException

2024-08-08 09:21 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +    public boolean emailDoctorExist (String email) {
doctorExists(String email)

2024-08-08 09:22 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +        if (emailDoctorExist(email)) {
zwykla edycja przez to nie zadziala ponieważ doktor ktory istnieje to wlasnie te ktory powinien zostac wywolany

2024-08-08 09:25 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/repository/PatientRepository.java
> +        if (editedPatient.getEmail().equals(email)) {
W sytuacji kiedy pacjent nie zmienai swojego maila -> podal taki sam to moim zdaniem nic to nie psuje

2024-08-08 09:27 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/repository/PatientRepository.java
> +        if (editedPatient.getEmail().equals(email)) {
if ( patientExists(editedPatient.getEmail()) && !email.equals(editedPatient.getEmail())   ) {
rzuc wyjatek

}

Jesli email na ktory pacjent chce sobie zmienic jest zajety i nie jest to jego email to wtedy rzuc wyjatek

2024-08-08 09:28 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +
nadmiarowa pusta linia

2024-08-08 09:29 UTC, konradgab commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +        if (doctorRepository.emailDoctorExist(doctor.getEmail())) {
ta metoda zrobiła nam się troche ifologią -> czy ta ifologia jest kluczowa w tym miejscu nie -> tutaj dobrze byłoby wyciągnąć te walidację do metody/metod i wywołać w tym meijscu po prostu metoda np. validateEditDoctorData(doctor);

2024-08-08 09:32 UTC, konradgab commented on src/medical-clinic/ChangingPassword.bru
>    name: ChangingPassword
Zmień miejsce w ktorym zapisywane są requesty z bruno na np. jakis folder nowy w ogole oddzielny od projektu i wszystkiego o nazwie req_bruno

2024-08-08 16:20 UTC, pmarko09 commented
Corrections mentioned in code review implemeted.

2024-08-09 08:35 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/controller/PatientController.java
> +    public Patient deleteDoctor(@PathVariable String email) {
zmień nazwę metody na pacjenta

2024-08-09 08:38 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +
nadmiarowa przerwa

2024-08-09 08:42 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/service/PatientService.java
> -        if (patient.getFirstName() == null) {
narazie używasz tego raz więc zmodyfikuj to na jedną metodę zamiast 3

2024-08-09 08:44 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/service/PatientService.java
> +    private void validatePatientFirstName(String firstName) {
przenieś metody prywatne na koniec kodu

2024-08-09 08:44 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +    private void validateDoctorFirstName(String firstName) {
przenieś metody prywatne na koniec kodu

2024-08-09 08:53 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/controller/PatientController.java
> +    public Patient deleteDoctor(@PathVariable String email) {
super komentarz, dzieki

2024-08-09 08:54 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +
racja

2024-08-09 08:54 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/service/PatientService.java
> -        if (patient.getFirstName() == null) {
dobra uwaga

2024-08-09 08:54 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/service/PatientService.java
> +    private void validatePatientFirstName(String firstName) {
ok

2024-08-09 08:54 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +    private void validateDoctorFirstName(String firstName) {
ok, dzieki

2024-08-09 09:07 UTC, pmarko09 commented on src/medical-clinic/ChangingPassword.bru
>    name: ChangingPassword
ok, dzieki, sprobuje z tym podzialac

2024-08-09 09:13 UTC, budzikovy requested changes

2024-08-09 09:13 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +
nadmiarowa linia

2024-08-09 09:13 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +        doctor.ifPresent(d -> d.setPassword(newPassword));
rozważ zmiane nazwy zmiennej d na przykład na doctor

2024-08-09 09:13 UTC, budzikovy commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +        validateDoctorFirstName(doctor.getFirstName());
możesz przenieść te 3 metody do jednej jeśli używasz tego tylko tutaj

2024-08-09 09:15 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/controller/DoctorController.java
> +
jasne

2024-08-09 09:15 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/repository/DoctorRepository.java
> +        doctor.ifPresent(d -> d.setPassword(newPassword));
ok, zmienie na doctor1, bo w Optionalu jest doctor

2024-08-09 09:32 UTC, pmarko09 commented on src/main/java/com/pmarko09/medical_clinic/service/DoctorService.java
> +        validateDoctorFirstName(doctor.getFirstName());
jasne, dodane tak jak z Patientem

2024-08-09 09:34 UTC, budzikovy approved these changes

2024-08-09 09:36 UTC, merged